# Generated by Django 5.1.1 on 2024-10-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_delete_carts_delete_orderedproduct_delete_orders_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
