# Generated by Django 5.1.1 on 2024-10-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
